---
# tasks file for terminate_ec2_instance

# - name: Terminate instances
#   hosts: localhost
#   connection: local
#   tasks:

- name: Terminate instances that were previously launched
  ec2:
    region: us-east-2
    state: 'absent'
    instance_ids: "{{ instance.instance_ids }}"
  


