---
# tasks file for terminate_ec2_instance

- name: Terminate instances that were previously launched
  ec2:
    region: "{{ region }}"
    instance_ids: "{{ ec2.instance_ids }}"
    state: 'absent'
    wait: True
  


