
---

- name: ec2 launcher
  hosts: localhost
  connection: local
  gather_facts: false

    

  roles:
    - security_group # creating new a test security group
    - ec2_instance # deploy ec2 instance
   # - terminate_ec2_instance # tasks file for terminate_ec2_instance


        

    