---

- name: Create a ec2 instance
  hosts: localhost
  gather_facts: False
 
  tasks:
    - name: Launch instance
      amazon.aws.ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         #vpc_subnet_id: subnet-29e63245
         assign_public_ip: yes
      register: ec2