---

- name: Create a ec2 instance
  hosts: localhost
  gather_facts: False
 
  tasks:
  - name: Launch instance
    # ec2:
    #   instance_type: t2.micro
    #   key_name: webserver
    #   image: ami-0d8d212151031f51c
    #   region: us-east-2
    #   wait: true
    #   group: default
    #   assign_public_ip: yes 
    # register: ec2
    amazon.aws.ec2:
      key_name: "{{ keypair }}"
      group: "{{ security_group }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      wait: true
      region: "{{ region }}"
     #vpc_subnet_id: subnet-29e63245
      #assign_public_ip: yes
    register: ec2